# Generated by Django 4.0.4 on 2022-06-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='pImage',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pizza',
            name='priceL',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='pizza',
            name='priceM',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
