# Generated by Django 4.0.4 on 2022-06-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_pizza_pimage_pizza_pricel_pizza_pricem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Burguer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('priceM', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('priceL', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('bImage', models.URLField(default='', max_length=255)),
            ],
        ),
    ]
